### ISSUE TITLE
What if payment failed

### ISSUE THREAD

**Issue by neoseeyou** [kmindi/wc-stripe-asynchronous-payments-pending-to-payment-complete#3]
Hello

Thank you for your plugin, i have one question.

What if the payment is contested  by the customer ?

Natively the order pass "on hold" then payment is clear by stripe 14days after order and we can processing the order. The order status change from "on hold" to "processing" then "completed".  

But it can happen that a customer contest the payment after that time, so the order status passed from "completed" to "on hold" again automatically

Will your plugin interfere with this native behaviour? 

Thank you !

**Comment by kmindi** [comment]
If a payment is set to payment complete or otherwise reached "completed" (by this plugin) and the delayed SEPA payment fails (e.g. because of a customer contest/challenge) the order status will still change to "failed".
I hope this answers your question?

**Comment by neoseeyou** [comment]
Thank you yes it's exactly what i want. Thank you
